### ISSUE TITLE
import statements must include "from x import y" at the top of the file .

### ISSUE THREAD

**Issue by tavaresrodrigo** [hugofco/Discount_Calculator#3]
Sharing a common style with the community facilitates collaboration with other developers. Prefer Absolute imports as they are usually more readable and tend to be better behaved. See [1] for more details. 

[1]https://peps.python.org/pep-0008/#imports

**Comment by hugofco** [comment]
Okay, I changed the imports in my code following the link you sent me. I found it interesting how I can import the package and then use it to import just the function I'm going to use, and with bigger codes or just the need to repeat the same function again it really makes more sense to insert some or the only function that will be used instead of repeating: package.function over and over again.

**Comment by tavaresrodrigo** [comment]
Looks good to me.

**Comment by tavaresrodrigo** [comment]
Looks Good to Me. Well done.
