### ISSUE TITLE
Structure Python Project repository

### ISSUE THREAD

**Issue by tavaresrodrigo** [hugofco/Discount_Calculator#4]
Let's improve the project structure, this article[1] suggests a good way to structure files and folders organised in a nice way in the filesystem.

Try to follow the recommendations on [1] and apply it to your project. 

[1]https://docs.python-guide.org/writing/structure/

**Comment by hugofco** [comment]
Ok, I improved the README file, now instead of just having a brief description of the project, it has a small text explaining the library that was used on the project, with a part of the code as an example of the use. I also added a simple installation guide. But it needs a little more work on the writing.

**Comment by tavaresrodrigo** [comment]
Well done, Hugo! The process to replicate the code in my own environment is clear now, the details you have provided will help other other developers that eventually want to contribute with your code.
